osx_image: xcode9.2
os: osx
sudo: required
language: js
cache:
  directories:
  - node_modules
  - bin
  - "$HOME/.electron"
  - "$HOME/.cache"
before_cache:
- rm -rf node_modules/.yarn-integrity
addons:
  apt:
    packages:
    - libgnome-keyring-dev
    - icnsutils
install:
- nvm install 9
- curl -o- -L https://yarnpkg.com/install.sh | bash
- source ~/.bashrc
- yarn global add xvfb-maybe
- yarn
script:
- yarn lint
- yarn unit
before_deploy:
- FORCE_DOWNLOAD=1 npm run download:bins
- yarn test:integration
- bash util_scripts/travis-number.sh
- yarn build
- mkdir binaries
- cp build/Mysterion-*.dmg binaries/Mysterion-latest.dmg
deploy:
  - provider: pages
    edge:
      branch: v1.8.47
    local-dir: binaries
    skip-cleanup: true
    github-token: "$GITHUB_API_TOKEN"
    keep-history: false
    target-branch: mysterion_$TRAVIS_OS_NAME
    repo: MysteriumNetwork/build-artifacts
    on:
      branch: master

notifications:
  slack:
    rooms:
      - secure: >
          gLtCJ8tQMJp4RUoeDSvZq+j9CY4p22gFu0gVZguHyxRSzRF5WaoJUdMRmILiYxPvyQ1LsD03XKr6nomRTJKz9uEWMOPcCZHclbkCDvYCbuGhF1
          mlGcUInTRdcqcBPbQYBTzXoJ8eeOM7l/LqdtoVM8AHsXh9SFNtsAUyqGS191sVwB9LEtAWGpOIraPVUSOh7g4I0P1ZLafH+9A0Ogpq4ca55nSi
          1B4+ld90zmlkiNJOaXvrSO9Vh7Sa7PhpWYvIeSFt1E8S8aUZeCxVupS9/s6CA7MHe3UZqS8+vwOnnYsWrskZwpbyBBDUswfyKiYBHVmy+gw8Hn
          mfQKzOgs5bs8a5kyrhh2aYtiIP978Ie6XOmjFv9c/k3F30f7f1RTzW8y/vhDxoBjLALpLfZ4daiXdQWbi8tj8JbrIKE8kc/cbyW+9EeG7ivURO
          cLyM+6deZbP1dIp8GPgdjyR7pkKsDc3CQuVjrXO8sTlcPvzrtd1D8M6n2SYywzT6WFXMHQkqQu+PxXirVGzFN86lz8XM4SoGs26z2OUBvHshqM
          b3CSvD5Yw/s1mHq2kUuYhQbHdGc4hnnz4nVG4A8ckiGQ9zsLDtTSRDLwaU42KJ2P99ApfkizFsycqmm5/jpssVe+wgH9cU1R5zaySwvZnK2FND
          wskSzB2t9ilnmKy4ABmw+08=
    on_success: change
    on_failure: always
